In [72]:
import pandas as pd
import numpy as np
import matplotlib .pyplot as plt
import matplotlib.image as mpimg

In [73]:
import cv2 
import os 
import glob 
img_dir = r"C:\Users\BSIS\male1" # Enter Directory of all images  
data_path = os.path.join(img_dir,'*g') 
files = glob.glob(data_path) 
data = [] 
for f1 in files: 
    img = cv2.imread(f1) 
    img.resize((200,200))
    data.append(img) 
    

In [74]:
data

[array([[208, 117,  90, ...,  75, 215, 117],
        [ 75, 215, 117, ..., 118,  90, 217],
        [118,  90, 217, ..., 211, 120,  93],
        ...,
        [247, 138, 250, ..., 123, 144, 206],
        [122, 143, 205, ..., 139, 228, 156],
        [138, 226, 157, ..., 132, 105, 222]], dtype=uint8),
 array([[217, 217, 223, ..., 127,  64,  81],
        [124,  61,  78, ...,  20,  24,  21],
        [ 20,  24,  23, ...,  51,  48,  63],
        ...,
        [ 25,  34,  27, ...,  38,  31,  36],
        [ 34,  27,  32, ..., 153,  88,  95],
        [134,  74,  80, ...,  26,  32,  38]], dtype=uint8),
 array([[ 21,  50,  55, ...,  96,  54,  75],
        [ 97,  56,  77, ..., 132, 160, 114],
        [136, 164, 114, ...,  71,  97, 114],
        ...,
        [165, 189, 123, ..., 169, 182, 204],
        [171, 184, 206, ...,  42,  26,  27],
        [ 37,  19,  21, ..., 145, 193, 122]], dtype=uint8),
 array([[136, 114, 102, ...,  79, 122, 103],
        [ 88, 123, 104, ..., 223, 200, 255],
        [225, 20

In [75]:
import cv2 
import os 
import glob 
img_dirs = r"C:\Users\BSIS\female1" # Enter Directory of all images  
data_paths = os.path.join(img_dirs,'*g') 
filess = glob.glob(data_paths) 
data1 = [] 
for f1 in filess: 
    imgs = cv2.imread(f1) 
    imgs.resize((200,200))
    data1.append(imgs) 

In [76]:
data1

[array([[ 57,  96,  50, ...,  15,  36,  61],
        [ 17, 107, 131, ...,  98,  26,  43],
        [ 93,  15,  37, ..., 146, 204, 199],
        ...,
        [ 85,  87,  46, ..., 160, 206, 230],
        [156, 202, 226, ..., 140,  63, 130],
        [145,  69, 132, ..., 106, 100, 130]], dtype=uint8),
 array([[121, 159, 191, ..., 206, 185, 210],
        [214, 193, 218, ..., 212, 223, 181],
        [213, 224, 180, ..., 104,  97,  82],
        ...,
        [220, 219, 206, ..., 134, 132, 138],
        [136, 136, 142, ...,  76,  36,  43],
        [ 40,  31,  36, ..., 214, 217, 196]], dtype=uint8),
 array([[191, 194, 209, ..., 212, 197, 201],
        [212, 196, 200, ..., 196, 211, 182],
        [187, 202, 178, ..., 173, 175, 185],
        ...,
        [167, 188, 162, ...,  32,  27,  26],
        [ 32,  27,  26, ..., 186, 166, 169],
        [184, 165, 168, ..., 177, 201, 179]], dtype=uint8),
 array([[ 79, 100,  97, ...,  70,  54,  73],
        [ 70,  54,  73, ...,  57,  54,  36],
        [ 57,  5

In [77]:
o=np.ones(20)
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [78]:
z=np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [79]:
x=data + data1
x

[array([[208, 117,  90, ...,  75, 215, 117],
        [ 75, 215, 117, ..., 118,  90, 217],
        [118,  90, 217, ..., 211, 120,  93],
        ...,
        [247, 138, 250, ..., 123, 144, 206],
        [122, 143, 205, ..., 139, 228, 156],
        [138, 226, 157, ..., 132, 105, 222]], dtype=uint8),
 array([[217, 217, 223, ..., 127,  64,  81],
        [124,  61,  78, ...,  20,  24,  21],
        [ 20,  24,  23, ...,  51,  48,  63],
        ...,
        [ 25,  34,  27, ...,  38,  31,  36],
        [ 34,  27,  32, ..., 153,  88,  95],
        [134,  74,  80, ...,  26,  32,  38]], dtype=uint8),
 array([[ 21,  50,  55, ...,  96,  54,  75],
        [ 97,  56,  77, ..., 132, 160, 114],
        [136, 164, 114, ...,  71,  97, 114],
        ...,
        [165, 189, 123, ..., 169, 182, 204],
        [171, 184, 206, ...,  42,  26,  27],
        [ 37,  19,  21, ..., 145, 193, 122]], dtype=uint8),
 array([[136, 114, 102, ...,  79, 122, 103],
        [ 88, 123, 104, ..., 223, 200, 255],
        [225, 20

In [1]:
x.shape

NameError: name 'x' is not defined

In [81]:
a=data+data1
a

[array([[208, 117,  90, ...,  75, 215, 117],
        [ 75, 215, 117, ..., 118,  90, 217],
        [118,  90, 217, ..., 211, 120,  93],
        ...,
        [247, 138, 250, ..., 123, 144, 206],
        [122, 143, 205, ..., 139, 228, 156],
        [138, 226, 157, ..., 132, 105, 222]], dtype=uint8),
 array([[217, 217, 223, ..., 127,  64,  81],
        [124,  61,  78, ...,  20,  24,  21],
        [ 20,  24,  23, ...,  51,  48,  63],
        ...,
        [ 25,  34,  27, ...,  38,  31,  36],
        [ 34,  27,  32, ..., 153,  88,  95],
        [134,  74,  80, ...,  26,  32,  38]], dtype=uint8),
 array([[ 21,  50,  55, ...,  96,  54,  75],
        [ 97,  56,  77, ..., 132, 160, 114],
        [136, 164, 114, ...,  71,  97, 114],
        ...,
        [165, 189, 123, ..., 169, 182, 204],
        [171, 184, 206, ...,  42,  26,  27],
        [ 37,  19,  21, ..., 145, 193, 122]], dtype=uint8),
 array([[136, 114, 102, ...,  79, 122, 103],
        [ 88, 123, 104, ..., 223, 200, 255],
        [225, 20

In [89]:
a=data+data1
x=np.array(a)


In [90]:
x.shape

(25, 200, 200)

In [95]:
x=x.reshape(25,200*200)
x

array([[208, 117,  90, ..., 132, 105, 222],
       [217, 217, 223, ...,  26,  32,  38],
       [ 21,  50,  55, ..., 145, 193, 122],
       ...,
       [191, 194, 209, ..., 177, 201, 179],
       [ 79, 100,  97, ...,   7,   1,   2],
       [ 19,  19,  19, ...,  89, 131,  81]], dtype=uint8)

In [96]:
x.shape

(25, 40000)

In [97]:
o=np.ones(20)
z=np.zeros(5)


In [68]:
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [69]:
z

array([0., 0., 0., 0., 0.])

In [98]:
y=np.append(o,z)

In [99]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 0., 0.])

In [100]:
y.shape

(25,)

In [104]:
from sklearn.model_selection import train_test_split

In [105]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y ,test_size=0.2,shuffle=True,random_state=None)

In [106]:
from sklearn import linear_model

In [107]:
model=linear_model.LinearRegression()

In [108]:
model.fit(xtrain,ytrain)

LinearRegression()

In [110]:
model.predict(xtest)

array([0.68842473, 0.51407721, 0.69297431, 0.84115219, 0.82024527])

In [111]:
model.score(xtest,ytest)

0.0

In [112]:
from sklearn.tree import DecisionTreeClassifier

In [115]:
dt= DecisionTreeClassifier()

In [116]:
dt.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [117]:
dt.predict(xtest)

array([1., 0., 0., 1., 1.])

In [118]:
dt.score(xtest,ytest)

0.6

In [122]:
from sklearn.ensemble import RandomForestClassifier

In [123]:
Rf=RandomForestClassifier()

In [124]:
Rf.fit(xtrain,ytrain)

RandomForestClassifier()

In [125]:
Rf.predict(xtest)

array([1., 1., 1., 1., 1.])

In [126]:
Rf.score(xtest,ytest)

1.0

In [131]:
from sklearn.svm import SVC

In [132]:
support=SVC()

In [133]:
support.fit(xtrain,ytrain)

SVC()

In [134]:
support.predict(xtest)

array([1., 1., 1., 1., 1.])

In [136]:
support.score(xtest,ytest)

1.0

In [138]:
from sklearn.neighbors import KNeighborsClassifier

In [139]:
KNN=KNeighborsClassifier()

In [140]:
KNN.fit(xtrain,ytrain)

KNeighborsClassifier()

In [141]:
KNN.predict(xtest)

array([0., 1., 1., 1., 1.])

In [142]:
KNN.score(xtest,ytest)

0.8

In [144]:
R={"LinearRegression":[model.score(xtest,ytest)],
    "support vectors machine":[support.score(xtest,ytest)],
   " KNeighborsClassifier":[KNN.score(xtest,ytest)],
   "RandomForestClassifier":[Rf.score(xtest,ytest)],
   "DecisionTreeClassifier":[dt.score(xtest,ytest)]
}

In [145]:
pd.DataFrame(R)

LinearRegression  support vectors machine   KNeighborsClassifier  \
0               0.0                      1.0                    0.8   

   RandomForestClassifier  DecisionTreeClassifier  
0                     1.0                     0.6